In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [2]:
x=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y=np.array([[0],[1],[1],[0]])
print(x)
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [3]:
def sig_act(z):
    return 1/(1+np.exp(-z))

def d_sig_act(z):
    return z*(1-z)

def sse(y, output):
    return np.sum(np.power(y-output,2))

In [4]:
class nn_toy:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.alphas = np.random.rand(self.x.shape[1],4)
        self.betas = np.random.rand(4,1)
        self.output = np.zeros(self.y.shape)
        
    def ff_process(self):
        self.H = sig_act(np.dot(self.x, self.alphas))
        self.output = sig_act(np.dot(self.H, self.betas))
        
    def bp_process(self):
        d_betas = np.dot(self.H.T, (2*(self.y - self.output) * d_sig_act(self.output)))
        d_alphas = np.dot(self.x.T, (np.dot(2 * (self.y - self.output) * 
                                            d_sig_act(self.output), self.betas.T) * 
                                        d_sig_act(self.H)))
        self.alphas += (d_alphas)
        self.betas += (d_betas)

In [5]:
toys = nn_toy(x,y)

for i in range(1500):
    toys.ff_process()
    toys.bp_process()
    print("SSE: ", sse(y,toys.output))
    
print("=======================================")
print(toys.output)

SSE:  1.4938219128685195
SSE:  1.251835119760115
SSE:  1.0507521691735404
SSE:  1.0033406599988952
SSE:  1.0009419674576447
SSE:  1.0007450283096229
SSE:  1.0006080472148433
SSE:  1.0004734675221583
SSE:  1.0003396513972338
SSE:  1.0002064044473458
SSE:  1.0000735710414532
SSE:  0.999940997777126
SSE:  0.9998085322263336
SSE:  0.9996760226096495
SSE:  0.9995433175008133
SSE:  0.9994102655354699
SSE:  0.9992767151222501
SSE:  0.9991425141553083
SSE:  0.9990075097274919
SSE:  0.9988715478433703
SSE:  0.9987344731313352
SSE:  0.9985961285540075
SSE:  0.9984563551161816
SSE:  0.9983149915695444
SSE:  0.9981718741133987
SSE:  0.9980268360906208
SSE:  0.9978797076780708
SSE:  0.9977303155706612
SSE:  0.9975784826582856
SSE:  0.9974240276947787
SSE:  0.9972667649580709
SSE:  0.9971065039006735
SSE:  0.9969430487896
SSE:  0.9967761983348168
SSE:  0.9966057453052597
SSE:  0.9964314761314421
SSE:  0.9962531704936255
SSE:  0.9960706008944898
SSE:  0.9958835322151869
SSE:  0.9956917212536196
SSE: 

In [6]:
toys = Sequential()
toys.add(Dense(units=3,activation='sigmoid',input_dim=3))
toys.add(Dense(units=1,activation='sigmoid'))
toys.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 12        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 16
Trainable params: 16
Non-trainable params: 0
_________________________________________________________________


In [7]:
toys.compile(loss='mean_squared_error', optimizer=SGD(learning_rate=1))
toys.fit(x,y,epochs=1500,verbose=0)

In [8]:
print(toys.predict(x))

1/1 [==============================] - 0s 118ms/step
[[0.06101269]
 [0.9307535 ]
 [0.94054663]
 [0.05634645]]
